import json
import os
import re
import sys
import time
from pathlib import Path
import requests

# Config from environment (set by chat.py)
LLAMA_SERVER = os.environ.get("AIOS_LLAMA_SERVER", "http://localhost:8083/v1/chat/completions")

# ---------------------------------------------------------------------------
# Typewriter sound (Wargames): tic per character, generated by the system
# ---------------------------------------------------------------------------

SOUND_ON = True
_AUDIO = None


def _open_audio():
    """Open a persistent aplay process (no files: synthesized PCM).
    Minimal ALSA buffer/period so each tic sounds immediately.
    Warm-up: 0.2 s of silence so ALSA opens the device BEFORE the first
    real tic (otherwise the first tics pile up in the pipe and sound late)."""
    global _AUDIO
    try:
        import subprocess as _sp
        _AUDIO = _sp.Popen(
            ["aplay", "-q", "-f", "S16_LE", "-r", "44100", "-c", "1", "-"],
            stdin=_sp.PIPE, stdout=_sp.DEVNULL, stderr=_sp.DEVNULL,
        )
        # Warm-up: force the device open (0.2 s of silence) before first real tic
        try:
            _AUDIO.stdin.write(b"\x00" * 17640)
            _AUDIO.stdin.flush()
            time.sleep(0.1)
        except Exception:
            pass
    except Exception:
        _AUDIO = None


def _tic():
    """Play a short synthesized 'tic' (850 Hz, 35 ms, smooth decay)."""
    if _AUDIO is None or _AUDIO.poll() is not None:
        return
    import math
    import struct
    sr, dur, freq = 44100, 0.035, 850.0
    n = int(sr * dur)
    pcm = bytearray()
    for i in range(n):
        t = i / sr
        env = math.exp(-t / 0.012)
        pcm += struct.pack("<h", int(12000 * env * math.sin(2 * math.pi * freq * t)))
    try:
        _AUDIO.stdin.write(bytes(pcm))
        _AUDIO.stdin.flush()
    except Exception:
        pass


def _skip_pressed():
    """True si el usuario pulso ESPACIO durante el typewriter (lo consume). No bloquea."""
    try:
        import select
        if select.select([0], [], [], 0)[0]:
            return os.read(0, 1) == b" "
    except Exception:
        pass
    return False


def _cbreak_on():
    """Activa modo cbreak (cada tecla al instante, sin echo) si hay tty.
    Devuelve (fd, old) para restaurar con _cbreak_off, o (None, None)."""
    try:
        import termios, tty
        fd = sys.stdin.fileno()
        old = termios.tcgetattr(fd)
        tty.setcbreak(fd)
        return fd, old
    except Exception:
        return None, None


def _cbreak_off(fd, old):
    if fd is not None:
        try:
            import termios
            termios.tcsetattr(fd, termios.TCSADRAIN, old)
        except Exception:
            pass


def _out(s=""):
    """Escribe a stdout convirtiendo LF en CRLF explicito (no depende de ONLCR
    del tty). El input (_input_tic) ya escribe CRLF explicito; la salida del LLM
    debe hacer lo mismo o el cursor no vuelve a la columna 0 -> efecto escalera."""
    sys.stdout.write(s.replace("\n", chr(13) + "\n"))
    sys.stdout.flush()


API_KEY = os.environ.get("AIOS_API_KEY", "")
AIOS_MODE = os.environ.get("AIOS_MODE", "local")
CLOUD_MODEL = os.environ.get("AIOS_CLOUD_MODEL", "")
AUTH_TYPE = os.environ.get("AIOS_CLOUD_AUTH", "bearer")
if API_KEY:
    CLOUD_HEADERS = {"X-API-Key": API_KEY} if AUTH_TYPE == "x-api-key" else {"Authorization": f"Bearer {API_KEY}"}
else:
    CLOUD_HEADERS = {}
# El ollama-hardened usa cert self-signed → desactivar verificación TLS solo en ese caso.
VERIFY_TLS = AUTH_TYPE != "x-api-key"
# Thinking mode local (binario). Qwen3 piensa por defecto; /no_think lo apaga.
# OFF (por defecto) -> rápido; ON -> el modelo razona antes de responder (más preciso, más lento).
THINK_LOCAL = os.environ.get("AIOS_LOCAL_THINK", "false").lower() in ("1", "true", "yes", "on")

MAX_TOKENS = 512
TEMPERATURE = 0.1
MAX_TURNS = 10
# Compression: 95% for local (RAM-derived), 50% for cloud (per-provider context_limit)
_LOCAL_CONTEXT = 32768
_cloud_context = int(os.environ.get("AIOS_CLOUD_CONTEXT", "128000"))


def _ram_gb():
    """RAM total en GB (redondeado) desde /proc/meminfo — mismo criterio que setup.py/status.py."""
    try:
        with open("/proc/meminfo", "r") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    kb = int(line.split()[1])
                    return max(1, kb // (1024 * 1024))
    except Exception:
        pass
    return 8


def _auto_context(ram_gb):
    """Auto-select context por RAM (espejo de setup.py auto_context)."""
    if ram_gb <= 8:
        return 8192
    elif ram_gb <= 16:
        return 32768
    else:
        return 65536


# Contexto local REAL según RAM del equipo (antes hardcodeado a 32K — bug latente
# en portátiles ≤8GB donde el servidor solo tiene 8K y la compresión usaba 32K)
_LOCAL_CONTEXT = _auto_context(_ram_gb())

# max_tokens relativo: cloud necesita margen para reasoning_content (DeepSeek gasta
# cientos de tokens pensando; 512 se agotaba → "respuesta vacía" con finish=length);
# local = 1/8 del contexto por RAM (deja 7/8 para system+tools+historial)
if os.environ.get("AIOS_MODE") in ("cloud", "hybrid"):
    MAX_TOKENS = 4096
else:
    MAX_TOKENS = max(512, _LOCAL_CONTEXT // 8)
    if THINK_LOCAL:
        # El razonamiento (<think>) consume tokens ANTES de la respuesta visible;
        # con poco presupuesto el modelo corta en finish=length y devuelve vacío.
        MAX_TOKENS = max(2048, _LOCAL_CONTEXT // 8)

MAX_HISTORY_TOKENS = int(_LOCAL_CONTEXT * 0.95) if os.environ.get("AIOS_MODE") in ("local", "hybrid") else int(_cloud_context * 0.50)
SESSION_FILE = Path("data") / f"session_{os.environ.get('AIOS_MODE', 'local')}.json"


def _estimate_tokens(text: str) -> int:
    """Estimate tokens via llama.cpp tokenize endpoint (accurate)."""
    try:
        resp = requests.post(
            LLAMA_SERVER + "/tokenize",
            json={"content": text},
            timeout=5
        )
        if resp.status_code == 200:
            return len(resp.json().get("tokens", []))
    except Exception:
        pass
    # Fallback: rough estimate
    return len(text) // 2


def _rules_common():
    # Solo decimos "no pienses" cuando el thinking está apagado. Si está encendido,
    # dejamos que Qwen3 razone (más preciso); el bloque <think> se limpia en _clean().
    _no_think = "" if THINK_LOCAL else "Do not use <think> tags.\n"
    return (
        "Always respond in the same language the user writes in.\n"
        "Be concise.\n"
        "For questions about the CURRENT state of the system (RAM, disk, processes, services, installed packages, network), ALWAYS check with a tool first — never answer from memory.\n"
        "For 'what programs/apps are installed' or 'is X installed', use the list_desktop_apps tool (never answer from memory).\n"
        "If you run a command, show its output to the user.\n"
        "Before destructive commands (rm -rf, dd, mkfs, fdisk), warn and ask for confirmation.\n"
        "If a command fails with Permission denied or Operation not permitted, retry it with sudo (passwordless sudo is available).\n"
        "If you don't know something, say so honestly: 'I don't know'.\n"
        + _no_think
        + "\nFor complex tasks, do NOT explain - EXECUTE. Generate a plan with numbered steps and execute each step automatically, verifying the result before continuing.\n"
        "NEVER end your turn with a promise to act ('I'll do it now', 'vamos a hacerlo', 'let me...'). If you intend to run a tool, emit the tool call in the SAME turn immediately — do not wait for the user to say 'ok'.\n"
        "Example:\n"
        "  User: \"install WordPress with Docker and MariaDB\"\n"
        "  Agent: run step 1 (check Docker), step 2 (create compose), step 3 (start), step 4 (verify). Without asking, without explaining. Just execute.\n"
        "\nIf a script expects interactive input (input(), confirmations, passwords), use process_start. Do NOT use run_command for interactive scripts."
    )

_AIOS_GROUNDING = """AIOS is Linux From Scratch (LFS), NOT Debian/Ubuntu/Arch/Fedora. Packages are managed ONLY with `sven`:
- `sven install <pkg>` / `sven remove <pkg>` / `sven search <q>` / `sven update` / `sven upgrade`
- `sven` requires root: ALWAYS run it with sudo (e.g. `sudo sven install docker`). It auto-confirms its prompts, so run it directly and wait for the result.
- There is NO apt/apt-get, NO dnf/yum, NO pacman. Never suggest them.

AIOS facts:
- Init: systemd (systemctl works).
- Desktop: Xorg + i3 (no GNOME/KDE).
- Network: systemd-networkd (ethernet + wifi DHCP); WiFi uses wpa_supplicant WITHOUT ctrl_interface — read SSID with `iw dev <iface> link`, never `wpa_cli`.
- Filesystem: usrmerge (binaries in /usr/bin, libs in /usr/lib).
- Update AIOS: `aios-update` (needs sudo). Install to disk: `aios-install`.
- Screen recording: $mod+Print toggles /tmp/grabacion.mp4.
- Local LLM: llama-server on 127.0.0.1:8083.

If unsure whether a package or command exists in AIOS, CHECK it (sven search / which) instead of guessing.

"""

_CLOUD_IDENTITY = """You are AIOS, the assistant of the AIOS operating system - a Linux distribution built from scratch (LFS) with a package layer managed by sven.

What you can do for the user:
- Run shell commands, read/write files, manage processes (start, PTY interaction).
- Search the web for information.
- Vision: read text from images (OCR - tesseract), take screenshots (scrot), control the desktop (xdotool).
- Install/remove packages with sven (official repositories only).
- Configure the system: network (WiFi, DNS), Xorg/i3 desktop, systemd services, the local LLM server (llama-server, port 8083).
- Screen recording: $mod+Print toggles recording of the screen (saved as a video file, e.g. /tmp/grabacion.mp4). Tell the user about it when they ask how to record the screen.
- Update AIOS itself: run 'aios-update' (updates agent, scripts and configs; requires internet and sudo).
- Answer questions, solve problems, automate tasks.

"""

_LOCAL_IDENTITY = """You are AIOS, the assistant of the AIOS Linux system (LFS + sven).
Expert Linux sysadmin. You can run commands, edit files, search the web, read text from images (OCR), take screenshots and control the desktop.
Screen recording: $mod+Print toggles recording of the screen (saved as a video file, e.g. /tmp/grabacion.mp4). Tell the user about it when they ask how to record the screen.
Update AIOS itself: run 'aios-update' (updates agent, scripts and configs; requires internet and sudo).

"""

SYSTEM_PROMPT = (_CLOUD_IDENTITY if os.environ.get("AIOS_MODE") in ("cloud", "hybrid") else _LOCAL_IDENTITY) + _AIOS_GROUNDING + _rules_common()

def _sampling_params():
    """Sampling: Qwen3 local sigue la doc oficial (thinking 0.6/0.95; no-thinking 0.7/0.8).
    Cloud mantiene temperatura conservadora — los modelos cloud ya vienen calibrados."""
    if os.environ.get("AIOS_MODE") == "cloud":
        return {"temperature": TEMPERATURE}
    if THINK_LOCAL:
        return {"temperature": 0.6, "top_p": 0.95, "top_k": 20, "min_p": 0.0}
    return {"temperature": 0.7, "top_p": 0.8, "top_k": 20, "min_p": 0.0}


from tools import TOOLS, execute_tool
from memory import ProceduralMemory


class Agent:
    SOUND_ON = True  # typewriter sound toggle (chat.py: /sound)

    def __init__(self):
        self.memory = ProceduralMemory()
        self.think = THINK_LOCAL
        self.messages = [{"role": "system", "content": SYSTEM_PROMPT}]
        self._load_session()

    def _quick_llm(self, prompt: str, tokens: int = 20, temp: float = 0.0) -> str:
        """Fast LLM without tools, for key generation and compression."""
        resp = requests.post(
            LLAMA_SERVER,
            json={"messages": [{"role": "user", "content": f"/no_think {prompt}"}],
                  "max_tokens": tokens, "temperature": temp},
            headers=CLOUD_HEADERS,
            timeout=15,
            verify=VERIFY_TLS,
        )
        data = resp.json()
        return data["choices"][0]["message"]["content"].strip()

    def _count_tokens(self, texts: list[str]) -> int:
        """Rough estimate: 4 chars ~= 1 token."""
        return sum(len(t) // 4 for t in texts)

    def _compress(self):
        """Compress history when approaching context limit. Keeps system prompt + last 3 exchanges."""
        all_text = "\n".join(m.get("content", "") for m in self.messages)
        total = _estimate_tokens(all_text)
        if total < MAX_HISTORY_TOKENS:
            return
        keep = [self.messages[0]]
        if len(self.messages) > 6:
            old = self.messages[1:-6]
            history_str = "\n".join(
                f"{m['role']}: {m['content'][:200]}" for m in old if m.get("content")
            )
            try:
                summary = self._quick_llm(
                    f"Resume the following conversation in 2-3 sentences keeping only technical details:\n\n{history_str}",
                    tokens=100, temp=0.3
                )
                keep.append({"role": "system", "content": f"[Summary: {summary}]"})
            except Exception:
                keep.append({"role": "system", "content": "[Previous conversation compressed]"})
            keep.extend(self.messages[-6:])
        else:
            keep = self.messages
        self.messages = keep

    def _save_session(self):
        """Saves the conversation history on exit."""
        SESSION_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(SESSION_FILE, "w", encoding="utf-8") as f:
            json.dump(self.messages, f, ensure_ascii=False)

    @staticmethod
    def _sanitize_messages(msgs):
        """Limpia el historial para que la API lo acepte (400 Bad Request si no):
        1. Assistant con tool_calls DEBE ir seguido de tool messages con cada tool_call_id.
           Si falta alguno, se elimina el assistant huérfano (esté donde esté).
        2. Tool messages sin su assistant previo se eliminan.
        3. Dos user seguidos se colapsan (se queda el último).
        """
        out = []
        pending_ids = set()
        orphan_idx = None  # índice en `out` del último assistant con tool_calls sin resolver
        for m in msgs:
            role = m.get("role")
            if role == "assistant" and m.get("tool_calls"):
                pending_ids = {tc.get("id") for tc in m["tool_calls"]}
                orphan_idx = len(out)
                out.append(m)
            elif role == "tool":
                if m.get("tool_call_id") in pending_ids:
                    pending_ids.discard(m["tool_call_id"])
                    if not pending_ids:
                        orphan_idx = None  # resuelto
                    out.append(m)
                else:
                    continue  # tool sin assistant previo → descartar
            else:
                # Llega un user/assistant normal con tool_calls sin resolver →
                # el assistant huérfano anterior se elimina
                if pending_ids and orphan_idx is not None:
                    out.pop(orphan_idx)
                    pending_ids = set()
                    orphan_idx = None
                if role == "user" and out and out[-1].get("role") == "user":
                    out[-1] = m  # colapsar user consecutivos
                else:
                    out.append(m)
        # Si al final quedan tool_calls sin respuesta, quitar el assistant huérfano
        if pending_ids and orphan_idx is not None:
            out.pop(orphan_idx)
        return out

    def _load_session(self):
        """Load the previous conversation history."""
        if SESSION_FILE.exists():
            try:
                old = json.loads(SESSION_FILE.read_text())
                # Mantener system prompt original, concatenar historial cargado
                loaded_messages = [m for m in old if m["role"] != "system"]
                loaded_messages = self._sanitize_messages(loaded_messages)
                self.messages.extend(loaded_messages)
                # Comprimir si el historial cargado es muy largo
                texts = [m.get("content", "") for m in self.messages]
                if self._count_tokens(texts) > MAX_HISTORY_TOKENS:
                    self._compress()
            except Exception:
                pass

    def _clean(self, text: str) -> str:
        """Limpia think blocks y normaliza."""
        text = re.sub(r"<think>.*?</think>\s*", "", text, flags=re.DOTALL).strip()
        return text

    def run(self, query: str) -> str:
        """Wrapper: marks the agent as busy (i3 status bar ⏳) and runs _run."""
        try:
            with open("/tmp/aios-agent.busy", "w") as f:
                f.write("1")
        except Exception:
            pass
        try:
            return self._run(query)
        finally:
            try:
                os.remove("/tmp/aios-agent.busy")
            except Exception:
                pass

    def _run(self, query: str) -> str:
        """Process a query with the function calling loop. First checks procedural memory."""
        if _AUDIO is None:
            _open_audio()
        # Comprimir historial si es necesario
        self._compress()

        # 1. Buscar en caché procedural (deshabilitado en modo cloud puro)
        if AIOS_MODE != "cloud":
            cached = self.memory.find(query, self._quick_llm)
            if cached:
                return f"[cache] {cached}"

        content = query if THINK_LOCAL else f"/no_think {query}"
        self.messages.append({"role": "user", "content": content})

        final_response = ""
        empty_retries = 0
        for _ in range(MAX_TURNS):
            # Sanitizar antes de cada POST: si una tool call quedó huérfana (stream
            # cortado o excepción a mitad), la API devolvería 400 Bad Request.
            self.messages = [self.messages[0]] + self._sanitize_messages(self.messages[1:])
            payload = {
                "messages": self.messages,
                "tools": TOOLS,
                "max_tokens": MAX_TOKENS,
                "stream": True,
                **_sampling_params(),
            }
            if AIOS_MODE in ("cloud", "hybrid") and CLOUD_MODEL:
                payload["model"] = CLOUD_MODEL

            try:
                resp = requests.post(LLAMA_SERVER, json=payload, headers=CLOUD_HEADERS, timeout=120, stream=True, verify=VERIFY_TLS)
                resp.raise_for_status()
            except Exception as e:
                return f"LLM connection error: {e}"

            content_chunks = []
            reasoning_chunks = []
            tool_calls_by_index = {}
            finish_reason = None
            stream_log = None
            fd_cb, old_cb = None, None

            try:
                # Log crudo del stream (diagnóstico del bug de respuesta vacía)
                try:
                    stream_log = open("/tmp/aios-stream.log", "a", encoding="utf-8", errors="replace")
                    stream_log.write(f"\n--- {time.strftime('%H:%M:%S')} mode={AIOS_MODE} ---\n")
                except Exception:
                    stream_log = None

                skip_rest = False  # espacio durante el typewriter -> imprimir el resto de golpe
                fd_cb, old_cb = _cbreak_on()

                for raw_line in resp.iter_lines():
                    if not raw_line:
                        continue
                    line = raw_line.decode("utf-8")
                    if stream_log:
                        stream_log.write(line + "\n")
                        stream_log.flush()
                    if not line.startswith("data: "):
                        continue
                    data_str = line[6:].strip()
                    if data_str == "[DONE]":
                        break
                    try:
                        data = json.loads(data_str)
                    except json.JSONDecodeError:
                        continue
                    for choice in data.get("choices", []):
                        delta = choice.get("delta", {})
                        if choice.get("finish_reason"):
                            finish_reason = choice["finish_reason"]
                        # Razonamiento del modelo (thinking) — se guarda para devolverlo en el turno
                        if "reasoning_content" in delta and delta["reasoning_content"]:
                            reasoning_chunks.append(delta["reasoning_content"])
                        # Live text (typewriter)
                        if "content" in delta and delta["content"]:
                            chunk = delta["content"]
                            content_chunks.append(chunk)
                            if skip_rest:
                                _out(chunk)
                            else:
                                for i, ch in enumerate(chunk):
                                    _out(ch)
                                    if _skip_pressed():
                                        _out(chunk[i + 1:])
                                        skip_rest = True
                                        break
                                    if self.SOUND_ON:
                                        _tic()
                                    time.sleep(0.02)
                        # Tool calls fragmentadas por índice
                        if "tool_calls" in delta:
                            for tc_delta in delta["tool_calls"]:
                                idx = tc_delta.get("index", 0)
                                if idx not in tool_calls_by_index:
                                    tool_calls_by_index[idx] = {
                                        "id": "",
                                        "type": "function",
                                        "function": {"name": "", "arguments": ""},
                                    }
                                if tc_delta.get("id"):
                                    tool_calls_by_index[idx]["id"] = tc_delta["id"]
                                func_delta = tc_delta.get("function", {})
                                if func_delta.get("name"):
                                    tool_calls_by_index[idx]["function"]["name"] += func_delta["name"]
                                if func_delta.get("arguments"):
                                    tool_calls_by_index[idx]["function"]["arguments"] += func_delta["arguments"]
                if stream_log:
                    stream_log.write(f"--- END finish={finish_reason} chunks={len(content_chunks)} tools={len(tool_calls_by_index)} ---\n")
            except Exception as e:
                if stream_log:
                    stream_log.write(f"--- EXC {type(e).__name__}: {e} ---\n")
                return f"Error leyendo stream del LLM: {e}"
            finally:
                if stream_log:
                    stream_log.close()
                _cbreak_off(fd_cb, old_cb)

            _out("\n")  # salto de línea tras el stream (CRLF explícito)
            content = "".join(content_chunks)
            reasoning = "".join(reasoning_chunks)
            msg = {"role": "assistant", "content": content or ""}
            if reasoning:
                msg["reasoning_content"] = reasoning
            if tool_calls_by_index:
                tool_calls = [tool_calls_by_index[i] for i in sorted(tool_calls_by_index)]
                msg["tool_calls"] = tool_calls
            finish = finish_reason or ""

            # Stream terminó sin contenido: reintentar UNA vez si (a) se cortó sin
            # finish_reason (conexión rota a mitad de tool call) o (b) finish=length
            # con content vacío (el modelo agotó max_tokens solo razonando — DeepSeek
            # reasoning_content). Con max_tokens ya ampliado esto es poco común.
            if (not finish or finish == "length") and not content and not msg.get("tool_calls") and empty_retries < 1:
                empty_retries += 1
                print("\n  Empty stream (possible cut or exhausted reasoning). Retrying...")
                continue

            # Tool call → ejecutar y devolver resultado al LLM
            if finish == "tool_calls" or msg.get("tool_calls"):
                assistant_msg = {"role": "assistant", "content": msg.get("content") or ""}
                if msg.get("reasoning_content"):
                    assistant_msg["reasoning_content"] = msg["reasoning_content"]
                if msg.get("tool_calls"):
                    assistant_msg["tool_calls"] = msg["tool_calls"]
                self.messages.append(assistant_msg)

                for tc in msg.get("tool_calls", []):
                    func = tc["function"]
                    name = func["name"]
                    try:
                        args = json.loads(func["arguments"])
                    except json.JSONDecodeError:
                        args = {}

                    # Anti-bucle: detect repeated tool calls (mismo tool + mismo comando base)
                    _last_call = getattr(self, '_last_tool', None)
                    _repeat_count = getattr(self, '_tool_repeat_count', 0)
                    _base = args.get('command', '')
                    if isinstance(_base, str) and _base.strip():
                        _base = _base.strip().split()[0]   # comando base (p.ej. 'ls')
                    _same = bool(_last_call and _last_call['name'] == name and _last_call['base'] == _base)
                    if _same:
                        self._tool_repeat_count = _repeat_count + 1
                    else:
                        self._tool_repeat_count = 0
                    self._last_tool = {'name': name, 'base': _base}

                    if self._tool_repeat_count >= 4:
                        print(f"  Same tool call {name} repeated {self._tool_repeat_count + 1} times")
                        print("  Abort the task? (y/N): ", end="", flush=True)
                        try:
                            import sys
                            import select
                            # 10s timeout
                            r, _, _ = select.select([sys.stdin], [], [], 10)
                            if r and sys.stdin.readline().strip().lower() == 'y':
                                return "Task aborted by the user after detecting a loop."
                        except:
                            pass

                    # Mostrar el tool ANTES de ejecutar (para que un comando largo
                    # no parezca que "no hace nada" — el ⚙ se ve inmediatamente).
                    _out(f"  ⚙ {name}({func.get('arguments','')})\n")
                    result = execute_tool(name, args, context=self.messages)
                    if name == "run_command":
                        r = json.loads(result)
                        out = (r.get('stdout', '') or '').rstrip()[:1000]
                        err = (r.get('stderr', '') or '').rstrip()[:300]
                        if out:
                            _out("     " + out.replace("\n", "\n     ") + "\n")
                        if err:
                            _out("     [stderr] " + err.replace("\n", "\n     ") + "\n")
                    self.messages.append({
                        "role": "tool",
                        "tool_call_id": tc.get("id", "call_0"),
                        "content": result
                    })
                continue  # siguiente iteración: LLM procesa el resultado

            # Respuesta final (texto)
            if msg.get("content"):
                final_response = self._clean(msg["content"])
                assistant_final = {"role": "assistant", "content": final_response}
                if msg.get("reasoning_content"):
                    assistant_final["reasoning_content"] = msg["reasoning_content"]
                self.messages.append(assistant_final)
                # If tools were used, store in procedural memory (only static knowledge)
                had_tools = any(m["role"] == "tool" for m in self.messages[-5:])
                had_dynamic = any("run_command" in m.get("content","") or "read_file" in m.get("content","")
                                  for m in self.messages[-5:])
                if had_tools and not had_dynamic and final_response and final_response != "I don't know":
                    self.memory.store(query, final_response, self._quick_llm)
                self._save_session()
                break
            else:
                final_response = "(empty model response)"
                break

        return final_response or "(no response)"

    def set_think(self, on: bool) -> bool:
        """Activa/desactiva el thinking en caliente (token + max_tokens + system prompt)."""
        global THINK_LOCAL, MAX_TOKENS, SYSTEM_PROMPT
        THINK_LOCAL = on
        self.think = on
        if os.environ.get("AIOS_MODE") in ("cloud", "hybrid"):
            MAX_TOKENS = 4096
        else:
            MAX_TOKENS = max(512, _LOCAL_CONTEXT // 8)
            if THINK_LOCAL:
                MAX_TOKENS = max(2048, _LOCAL_CONTEXT // 8)
        SYSTEM_PROMPT = (_CLOUD_IDENTITY if os.environ.get("AIOS_MODE") in ("cloud", "hybrid") else _LOCAL_IDENTITY) + _AIOS_GROUNDING + _rules_common()
        if self.messages and self.messages[0].get("role") == "system":
            self.messages[0] = {"role": "system", "content": SYSTEM_PROMPT}
        return on

    def reset(self):
        """Reinicia la conversación."""
        self.messages = [{"role": "system", "content": SYSTEM_PROMPT}]
