import json
import os
import re
import sys
import time
from pathlib import Path
import requests

# Config from environment (set by chat.py)
LLAMA_SERVER = os.environ.get("AIOS_LLAMA_SERVER", "http://localhost:8083/v1/chat/completions")

# ---------------------------------------------------------------------------
# Typewriter sound (Wargames): tic per character, generated by the system
# ---------------------------------------------------------------------------

SOUND_ON = True
_AUDIO = None


def _open_audio():
    """Open a persistent aplay process (no files: synthesized PCM).
    Minimal ALSA buffer/period so each tic sounds immediately.
    Warm-up: 0.2 s of silence so ALSA opens the device BEFORE the first
    real tic (otherwise the first tics pile up in the pipe and sound late)."""
    global _AUDIO
    try:
        import subprocess as _sp
        _AUDIO = _sp.Popen(
            ["aplay", "-q", "--period-size=128", "--buffer-size=256", "-f", "S16_LE", "-r", "44100", "-c", "1", "-"],
            stdin=_sp.PIPE, stdout=_sp.DEVNULL, stderr=_sp.DEVNULL,
        )
        # Warm-up: force the device open (0.2 s of silence) before first real tic
        try:
            _AUDIO.stdin.write(b"\x00" * 17640)
            _AUDIO.stdin.flush()
            time.sleep(0.1)
        except Exception:
            pass
    except Exception:
        _AUDIO = None


def _close_audio():
    """Close the persistent aplay (frees the PCM device for TTS)."""
    global _AUDIO
    if _AUDIO is not None:
        try:
            _AUDIO.stdin.close()
        except Exception:
            pass
        try:
            _AUDIO.terminate()
        except Exception:
            pass
        _AUDIO = None


def _reopen_audio():
    """Reopen the persistent aplay after TTS (device was busy)."""
    _open_audio()


def _tic():
    """Play a teletype-style 'tick': a very short high transient (4 kHz noise,
    1.5 ms) followed by a low body (250 Hz sine, 8 ms). Mimics the classic
    Wargames terminal clack. Synthesized in memory (no files)."""
    if _AUDIO is None or _AUDIO.poll() is not None:
        return
    import math
    import random
    import struct
    sr = 44100

    def _bandpass(x, center, Q):
        w0 = 2 * math.pi * center / sr
        alpha = math.sin(w0) / (2 * Q)
        b0, b1, b2 = alpha, 0.0, -alpha
        a0, a1, a2 = 1 + alpha, -2 * math.cos(w0), 1 - alpha
        b0, b1, b2 = b0 / a0, b1 / a0, b2 / a0
        a1, a2 = a1 / a0, a2 / a0
        y = [0.0] * len(x)
        x1 = x2 = y1 = y2 = 0.0
        for i, v in enumerate(x):
            y0 = b0 * v + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
            x2, x1 = x1, v
            y2, y1 = y1, y0
            y[i] = y0
        return y

    # Transient: 1.5 ms noise, very fast decay, bandpass 4 kHz
    n1 = int(sr * 0.0015)
    click = [(random.random() * 2 - 1) * math.exp(-i / 5.0) for i in range(n1)]
    click = _bandpass(click, 4000.0, 8.0)
    # Body: 250 Hz sine, 8 ms, fast decay
    n2 = int(sr * 0.008)
    body = [math.sin(2 * math.pi * 250 * i / sr) * math.exp(-i / (sr * 0.0018)) for i in range(n2)]
    # Assemble: click + tiny gap + body
    samples = list(click) + [0.0] * int(sr * 0.0005) + [b * 0.5 for b in body]
    gain = 0.19
    pcm = bytearray()
    for s in samples:
        pcm += struct.pack("<h", int(max(-1.0, min(1.0, s)) * gain * 32767))
    try:
        _AUDIO.stdin.write(bytes(pcm))
        _AUDIO.stdin.flush()
    except Exception:
        pass


def _skip_pressed():
    """True if the user pressed SPACE during the typewriter (consumes it). Non-blocking."""
    try:
        import select
        if select.select([0], [], [], 0)[0]:
            return os.read(0, 1) == b" "
    except Exception:
        pass
    return False


def _read_key():
    """Non-blocking read of ONE raw key during the typewriter (cbreak mode).
    Returns the byte (b" ", b"\t", b"\x12"...) or None if no key pressed.
    Used for barge-in: Tab = add text info, Ctrl+R = add voice info."""
    try:
        import select
        if select.select([0], [], [], 0)[0]:
            return os.read(0, 1)
    except Exception:
        pass
    return None


def _barge_input(prompt="  » "):
    """Raw line input for barge-in text (no tic, no history).
    Called AFTER the typewriter stops, with the terminal restored."""
    import termios, tty
    fd = sys.stdin.fileno()
    old = termios.tcgetattr(fd)
    sys.stdout.write(prompt)
    sys.stdout.flush()
    buf = []
    try:
        tty.setraw(fd)
        while True:
            ch = sys.stdin.read(1)
            if ch in ("\r", "\n"):
                sys.stdout.write("\r\n")
                sys.stdout.flush()
                break
            if ch in ("\x03", "\x04"):  # Ctrl+C / Ctrl+D cancels
                sys.stdout.write("\r\n")
                sys.stdout.flush()
                return ""
            if ch in ("\x7f", "\x08"):  # backspace
                if buf:
                    buf.pop()
                    sys.stdout.write("\b \b")
                    sys.stdout.flush()
            elif ch.isprintable():
                buf.append(ch)
                sys.stdout.write(ch)
                sys.stdout.flush()
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old)
    return "".join(buf)


def _cbreak_on():
    """Enable cbreak mode (each key is available instantly, no echo) if there is a tty.
    Returns (fd, old) to restore with _cbreak_off, or (None, None)."""
    try:
        import termios, tty
        fd = sys.stdin.fileno()
        old = termios.tcgetattr(fd)
        tty.setcbreak(fd)
        return fd, old
    except Exception:
        return None, None


def _cbreak_off(fd, old):
    if fd is not None:
        try:
            import termios
            termios.tcsetattr(fd, termios.TCSADRAIN, old)
        except Exception:
            pass


def _out(s=""):
    """Write to stdout converting LF to explicit CRLF (does not depend on ONLCR
    of the tty). The input (_input_tic) already writes explicit CRLF; LLM output
    must do the same or the cursor will not return to column 0 -> staircase effect."""
    sys.stdout.write(s.replace("\n", chr(13) + "\n"))
    sys.stdout.flush()


API_KEY = os.environ.get("AIOS_API_KEY", "")
AIOS_MODE = os.environ.get("AIOS_MODE", "local")
CLOUD_MODEL = os.environ.get("AIOS_CLOUD_MODEL", "")
AUTH_TYPE = os.environ.get("AIOS_CLOUD_AUTH", "bearer")
if API_KEY:
    CLOUD_HEADERS = {"X-API-Key": API_KEY} if AUTH_TYPE == "x-api-key" else {"Authorization": f"Bearer {API_KEY}"}
else:
    CLOUD_HEADERS = {}
# TLS verification: enabled by default (Cloudflare serves a valid cert on :443).
# Set AIOS_CLOUD_VERIFY=0 only for self-signed endpoints.
VERIFY_TLS = os.environ.get("AIOS_CLOUD_VERIFY", "1") in ("1", "true", "yes", "on")
# Thinking mode local (binary). Qwen3.5 thinks by default; enable_thinking controls it.
# OFF (default) -> fast; ON -> model reasons before answering (more accurate, slower).
THINK_LOCAL = os.environ.get("AIOS_LOCAL_THINK", "false").lower() in ("1", "true", "yes", "on")

MAX_TOKENS = 512
TEMPERATURE = 0.1
MAX_TURNS = 25
# Compression: 95% for local (RAM-derived), 50% for cloud (per-provider context_limit)
_LOCAL_CONTEXT = 32768
_cloud_context = int(os.environ.get("AIOS_CLOUD_CONTEXT", "128000"))


def _ram_gb():
    """Total RAM in GB (rounded) from /proc/meminfo — same criterion as setup.py/status.py."""
    try:
        with open("/proc/meminfo", "r") as f:
            for line in f:
                if line.startswith("MemTotal:"):
                    kb = int(line.split()[1])
                    return max(1, kb // (1024 * 1024))
    except Exception:
        pass
    return 8


def _auto_context(ram_gb):
    """Auto-select context by RAM (mirror of setup.py auto_context)."""
    if ram_gb <= 8:
        return 8192
    elif ram_gb <= 16:
        return 32768
    else:
        return 65536


# Real local context according to the machine's RAM (was hardcoded to 32K — latent bug
# on ≤8GB laptops where the server only has 8K and compression used 32K)
_LOCAL_CONTEXT = _auto_context(_ram_gb())

# Relative max_tokens: cloud needs margin for reasoning_content (DeepSeek can spend
# hundreds of tokens thinking; 512 ran out → "empty response" with finish=length);
# local = 1/8 of RAM-derived context (leaves 7/8 for system+tools+history)
if os.environ.get("AIOS_MODE") in ("cloud", "hybrid"):
    MAX_TOKENS = max(4096, _cloud_context // 4)
else:
    MAX_TOKENS = max(512, _LOCAL_CONTEXT // 8)
    if THINK_LOCAL:
        # Reasoning (thinking) consumes tokens BEFORE the visible response;
        # with a small budget the model stops at finish=length and returns empty.
        MAX_TOKENS = max(2048, _LOCAL_CONTEXT // 8)

MAX_HISTORY_TOKENS = int(_LOCAL_CONTEXT * 0.95) if os.environ.get("AIOS_MODE") in ("local", "hybrid") else int(_cloud_context * 0.06)
SESSION_FILE = Path("data") / f"session_{os.environ.get('AIOS_MODE', 'local')}.json"


def _estimate_tokens(text: str) -> int:
    """Estimate tokens via llama.cpp tokenize endpoint (accurate)."""
    try:
        resp = requests.post(
            LLAMA_SERVER + "/tokenize",
            json={"content": text},
            timeout=5
        )
        if resp.status_code == 200:
            return len(resp.json().get("tokens", []))
    except Exception:
        pass
    # Fallback: rough estimate. len//2 OVERESTIMATES for natural text in all
    # European languages (measured 2.8-4.4 chars/token) and matches technical
    # content (~2 chars/token). Overestimating is safe: compression triggers
    # early, never late (Cloudflare 100s limit).
    return len(text) // 2


def _rules_common():
    # Only say "do not think" when thinking is off. When it is on, let Qwen3 reason
    # (more accurate); the thinking block is cleaned in _clean().
    _no_think = ""  # thinking is controlled via chat_template_kwargs (enable_thinking), not <think> tags
    return (
        "Always respond in the same language the user writes in.\n"
        "Be concise.\n"
        "For questions about the CURRENT state of the system (RAM, disk, processes, services, installed packages, network), ALWAYS check with a tool first — never answer from memory.\n"
        "For 'what programs/apps are installed' or 'is X installed', use the list_desktop_apps tool (never answer from memory).\n"
        "If you run a command, show its output to the user.\n"
        "Before destructive commands (rm -rf, dd, mkfs, fdisk), warn and ask for confirmation.\n"
        "If a command fails with Permission denied or Operation not permitted, retry it with sudo. When you run a command with sudo, the system will automatically ask the user for the sudo password (masked) if it is needed — do NOT ask the user to run /sudo or to type a password; just emit the sudo command and it will be handled.\n"
        "If a systemd service fails to start with 'A dependency job for ... failed', do NOT run the same `systemctl start` again. Inspect the failing dependency first with `systemctl status <dependency>` and `journalctl -u <dependency> --no-pager`. If the failure is due to the live session (e.g. Docker socket cannot bind in overlay), tell the user and stop.\n"
        "If you don't know something, say so honestly: 'I don't know'.\n"
        + _no_think
        + "\nFor complex tasks, do NOT explain - EXECUTE. Generate a plan with numbered steps and execute each step automatically, verifying the result before continuing.\n"
        "NEVER end your turn with a promise to act ('I'll do it now', 'vamos a hacerlo', 'let me...'). If you intend to run a tool, emit the tool call in the SAME turn immediately — do not wait for the user to say 'ok'.\n"
        "Example:\n"
        "  User: \"install WordPress with Docker and MariaDB\"\n"
        "  Agent: run step 1 (check Docker), step 2 (create compose), step 3 (start), step 4 (verify). Without asking, without explaining. Just execute.\n"
        "\nIf a script expects interactive input (input(), confirmations, passwords), use process_start. Do NOT use run_command for interactive scripts."
    )


def _is_trivial_query(q: str) -> bool:
    """True for greetings/acknowledgements/short queries — not reusable
    procedure knowledge worth caching in procedural memory."""
    _TRIVIAL = {"hola", "buenas", "hello", "hi", "hey", "gracias", "thanks",
                "ok", "vale", "si", "s\u00ed", "adelante", "perfecto", "genial"}
    qn = re.sub(r"[^a-z\u00e1\u00e9\u00ed\u00f3\u00fa\u00f1\u00fc0-9 ]", "", q.lower()).strip()
    if len(qn) < 12:
        return True
    words = set(qn.split())
    if words & _TRIVIAL:
        return True
    return False


_AIOS_GROUNDING = """AIOS is Linux From Scratch (LFS), NOT Debian/Ubuntu/Arch/Fedora. Packages are managed ONLY with `sven`:
- `sven install <pkg>` / `sven remove <pkg>` / `sven search <q>` / `sven update` / `sven upgrade`
- `sven` requires root: ALWAYS run it with sudo (e.g. `sudo sven install docker`). It auto-confirms its prompts, so run it directly and wait for the result.
- There is NO apt/apt-get, NO dnf/yum, NO pacman. Never suggest them.

AIOS facts:
- Init: systemd (systemctl works).
- Desktop: Xorg + i3 (no GNOME/KDE).
- Network: systemd-networkd (ethernet + wifi DHCP); WiFi uses wpa_supplicant WITHOUT ctrl_interface — read SSID with `iw dev <iface> link`, never `wpa_cli`.
- Filesystem: usrmerge (binaries in /usr/bin, libs in /usr/lib).
- Update AIOS: `aios-update` (needs sudo). Install to disk: `aios-install`.
- Screen recording: $mod+Print toggles /tmp/grabacion.mp4.
- Local LLM: llama-server on 127.0.0.1:8083.

If unsure whether a package or command exists in AIOS, CHECK it (sven search / which) instead of guessing.

"""

_CLOUD_IDENTITY = """You are AIOS, the assistant of the AIOS operating system - a Linux distribution built from scratch (LFS) with a package layer managed by sven.

What you can do for the user:
- Run shell commands, read/write files, manage processes (start, PTY interaction).
- Search the web for information.
- Vision: read text from images (OCR - tesseract), take screenshots (scrot), control the desktop (xdotool).
  To SEE the screen, use in order of preference: 1) describe_screen() (if vision.enabled in config), 2) browser_eval/browser_elements to read a web app's DOM, 3) ocr — ONLY to extract text from an image file you already have, 4) screenshot — ONLY to save evidence, not to "see". Never call screenshot/ocr first to "look at the screen".
- Web browsing: use Chromium with the browser_* tools (browser_navigate, browser_eval, browser_elements, browser_click, browser_type). They read the real page DOM — no OCR needed. NEVER try to control a browser by writing to its stdin (browsers ignore it). Use xdotool/OCR only as a last resort.
  Browser workflow: browser_navigate(url) to open a page, then browser_elements() to SEE the interactive elements — ALWAYS call this before clicking/typing. browser_click/browser_type accept a CSS selector OR the visible text (e.g. "Configure visualization", "Create your first dashboard"). IGNORE the ref field of browser_elements (it is only a human-readable label, not a selector); use the element's visible text or the selector field instead. If a click/type returns NOT_FOUND, re-run browser_elements() to see the current page state (it may have changed after navigation) and pick the right text/selector — do NOT guess refs or CSS selectors. browser_eval("document.body.innerText") reads the visible text, browser_eval("document.title") the title. Example: to search flights, navigate to the site, call browser_elements() to find the cookie-accept button and the search inputs, click/type by their visible text, and read the results.
  IMPORTANTE browser_eval: devuelve el VALOR DE RETORNO de la expresión, NO la salida de console.log (console.log devuelve null siempre). Para listar botones/inputs usa expresiones que DEVUELVAN: Array.from(document.querySelectorAll('button')).map((b,i)=>i+':'+b.textContent.trim()).filter(x=>x).join('\\n'). NO uses console.log.
  API-FIRST: para apps web con API (Grafana, Prometheus, Jenkins, GitLab, etc.) y la página YA autenticada, usa fetch() desde browser_eval para crear/configurar recursos directamente — es más rápido y fiable que clicar la UI. Ejemplo: fetch('/api/dashboards/db', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({...})}).then(r=>r.json()). El fetch corre en el MISMO origen → lleva las cookies de sesión → no necesita credenciales. Usa la UI solo para lo que la API no permita.
  Para tareas de UI complejas (crear dashboards, formularios multi-paso): trabaja en PASOS PEQUEÑOS — una acción por turno de tool, verifica (browser_eval document.URL + título, o browser_elements) y continúa. No intentes hacer todo en una sola llamada.
- Install/remove packages with sven (official repositories only).
- Configure the system: network (WiFi, DNS), Xorg/i3 desktop, systemd services, the local LLM server (llama-server, port 8083).
- Screen recording: $mod+Print toggles recording of the screen (saved as a video file, e.g. /tmp/grabacion.mp4). Tell the user about it when they ask how to record the screen.
- Update AIOS itself: run 'aios-update' (updates agent, scripts and configs; requires internet and sudo).
- Answer questions, solve problems, automate tasks.

"""

_LOCAL_IDENTITY = """You are AIOS, the assistant of the AIOS Linux system (LFS + sven).
Expert Linux sysadmin. You can run commands, edit files, search the web, read text from images (OCR), take screenshots and control the desktop.
- Web browsing: use Chromium with the browser_* tools (browser_navigate, browser_eval, browser_elements, browser_click, browser_type). They read the real page DOM — no OCR needed. NEVER try to control a browser by writing to its stdin (browsers ignore it). Use xdotool/OCR only as a last resort.
  Browser workflow: browser_navigate(url) to open a page, then browser_elements() to SEE the interactive elements — ALWAYS call this before clicking/typing. browser_click/browser_type accept a CSS selector OR the visible text (e.g. "Configure visualization", "Create your first dashboard"). IGNORE the ref field of browser_elements (it is only a human-readable label, not a selector); use the element's visible text or the selector field instead. If a click/type returns NOT_FOUND, re-run browser_elements() to see the current page state (it may have changed after navigation) and pick the right text/selector — do NOT guess refs or CSS selectors. browser_eval("document.body.innerText") reads the visible text, browser_eval("document.title") the title. Example: to search flights, navigate to the site, call browser_elements() to find the cookie-accept button and the search inputs, click/type by their visible text, and read the results.
  IMPORTANTE browser_eval: devuelve el VALOR DE RETORNO de la expresión, NO la salida de console.log (console.log devuelve null siempre). Para listar botones/inputs usa expresiones que DEVUELVAN: Array.from(document.querySelectorAll('button')).map((b,i)=>i+':'+b.textContent.trim()).filter(x=>x).join('\\n'). NO uses console.log.
  API-FIRST: para apps web con API (Grafana, Prometheus, Jenkins, GitLab, etc.) y la página YA autenticada, usa fetch() desde browser_eval para crear/configurar recursos directamente — es más rápido y fiable que clicar la UI. Ejemplo: fetch('/api/dashboards/db', {method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({...})}).then(r=>r.json()). El fetch corre en el MISMO origen → lleva las cookies de sesión → no necesita credenciales. Usa la UI solo para lo que la API no permita.
  Para tareas de UI complejas (crear dashboards, formularios multi-paso): trabaja en PASOS PEQUEÑOS — una acción por turno de tool, verifica (browser_eval document.URL + título, o browser_elements) y continúa. No intentes hacer todo en una sola llamada.
Screen recording: $mod+Print toggles recording of the screen (saved as a video file, e.g. /tmp/grabacion.mp4). Tell the user about it when they ask how to record the screen.
Update AIOS itself: run 'aios-update' (updates agent, scripts and configs; requires internet and sudo).

"""

SYSTEM_PROMPT = (_CLOUD_IDENTITY if os.environ.get("AIOS_MODE") in ("cloud", "hybrid") else _LOCAL_IDENTITY) + _AIOS_GROUNDING + _rules_common()

def _sampling_params():
    """Sampling: Qwen3 local follows official docs (thinking 0.6/0.95; no-thinking 0.7/0.8).
    Cloud keeps conservative temperature — cloud models are already calibrated."""
    if os.environ.get("AIOS_MODE") == "cloud":
        return {"temperature": TEMPERATURE}
    if THINK_LOCAL:
        return {"temperature": 0.6, "top_p": 0.95, "top_k": 20, "min_p": 0.0}
    return {"temperature": 0.7, "top_p": 0.8, "top_k": 20, "min_p": 0.0}


def _empty_reason(finish: str, reasoning_chunks: list) -> str:
    """Human-readable cause of a content-less response (diagnostic)."""
    r = len("".join(reasoning_chunks)) if reasoning_chunks else 0
    if finish == "length":
        s = "finish_reason=length: token/context budget exhausted"
        if r:
            s += f" ({r} reasoning chars emitted first)"
        s += " — raise num_ctx/max_tokens"
        return s
    if finish:
        return f"finish_reason={finish} with no content"
    return "no finish_reason (stream cut?)"


from tools import TOOLS, execute_tool
from memory import ProceduralMemory


class Agent:
    SOUND_ON = True  # typewriter sound toggle (chat.py: /sound)

    def __init__(self):
        self.memory = ProceduralMemory()
        self.think = THINK_LOCAL
        self.messages = [{"role": "system", "content": SYSTEM_PROMPT}]
        self._load_session()

    def _quick_llm(self, prompt: str, tokens: int = 20, temp: float = 0.0) -> str:
        """Fast LLM without tools, for key generation and compression."""
        resp = requests.post(
            LLAMA_SERVER,
            json={"messages": [{"role": "user", "content": prompt}],
                  "max_tokens": tokens, "temperature": temp,
                  "chat_template_kwargs": {"enable_thinking": False}},
            headers=CLOUD_HEADERS,
            timeout=15,
            verify=VERIFY_TLS,
        )
        data = resp.json()
        return data["choices"][0]["message"]["content"].strip()

    def _count_tokens(self, texts: list[str]) -> int:
        """Rough estimate: 4 chars ~= 1 token."""
        return sum(len(t) // 4 for t in texts)

    def _compress(self):
        """Compress history when approaching context limit. Keeps system prompt + last 3 exchanges.
        Loops (max 3 passes) so the final prompt always fits under the Cloudflare 100s
        budget regardless of language (len//2 overestimates, so it converges)."""
        for _pass in range(3):
            all_text = "\n".join(m.get("content", "") for m in self.messages)
            total = _estimate_tokens(all_text)
            if total < MAX_HISTORY_TOKENS:
                return
            keep = [self.messages[0]]
            if len(self.messages) > 6:
                old = self.messages[1:-6]
                history_str = "\n".join(
                    f"{m['role']}: {m['content'][:200]}" for m in old if m.get("content")
                )[-2000:]  # cap: keep the compression call light (Cloudflare 100s)
                try:
                    # Extract real keywords from the old messages BEFORE asking
                    # the LLM to summarize. Reasoning models can
                    # fabricate a plausible-but-false summary (verified 9 Sep
                    # 2026: it invented a Node.js/Express/MongoDB conversation
                    # that never happened). We only accept a summary that
                    # actually mentions the real topics.
                    import re as _re
                    _words = _re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", history_str.lower())
                    _stop = {"the", "and", "for", "with", "that", "this", "you", "your",
                             "was", "are", "not", "but", "from", "have", "has", "had",
                             "will", "would", "can", "could", "should", "into", "them",
                             "then", "than", "they", "there", "their", "what", "when",
                             "where", "which", "while", "who", "why", "how", "all",
                             "any", "are", "been", "being", "both", "did", "does",
                             "doing", "each", "few", "more", "most", "other", "some",
                             "such", "only", "own", "same", "so", "than", "too", "very",
                             "just", "about", "after", "also", "because", "before",
                             "between", "during", "through", "under", "again", "once",
                             "here", "there", "out", "up", "down", "off", "over", "under"}
                    # Roles and tool names are noise, not topics — never use them
                    # as grounding keywords.
                    _stop |= {"user", "assistant", "tool", "browser", "browser_click",
                              "browser_eval", "browser_elements", "browser_navigate",
                              "browser_type", "run_command", "read_file", "write_file",
                              "get_installed_info", "screenshot", "ocr", "xdotool",
                              "process_start", "process_list",
                              "list_desktop_apps", "web_search", "get_context_usage",
                              "cloud_reasoning", "error", "result", "ok", "true", "false"}
                    _kw = [w for w in _words if w not in _stop]
                    # Stable top-N: sort once by frequency, keep order ties stable
                    # (set() would shuffle and could drop the real topic keyword).
                    _freq = {}
                    for w in _kw:
                        _freq[w] = _freq.get(w, 0) + 1
                    _kw = sorted(_freq.items(), key=lambda kv: (-kv[1], kv[0]))[:12]
                    _kw = [w for w, _ in _kw]
                    summary = self._quick_llm(
                        f"Resume the following conversation in 2-3 sentences keeping only technical details:\n\n{history_str}",
                        tokens=100, temp=0.3
                    )
                    # Verify the summary is grounded: it must mention at least 2
                    # of the real keywords. Otherwise the model hallucinated —
                    # fall back to an honest generic summary.
                    _sl = summary.lower()
                    _hits = sum(1 for w in _kw if w in _sl)
                    if _hits < 2 or not _kw:
                        summary = ("[Previous conversation summary: se estaba trabajando en una tarea "
                                   "con herramientas (browser, comandos, archivos). El detalle exacto se "
                                   "perdió en la compresión — pide al usuario que re-explique si hace falta.]")
                    keep.append({"role": "user", "content": f"[Previous conversation summary: {summary}]"})
                except Exception:
                    keep.append({"role": "user", "content": "[Previous conversation compressed]"})
                # Keep the most recent exchange verbatim, but drop older tool outputs
                # (already summarized) so tool-heavy sessions do not bloat the context.
                take = self.messages[-6:]
                last_tool = max((i for i, m in enumerate(take) if m.get("role") == "tool"), default=None)
                if last_tool is not None:
                    take = take[max(0, last_tool - 1):]
                keep.extend(take)
            else:
                keep = self.messages
            self.messages = keep

    def _save_session(self):
        """Saves the conversation history on exit."""
        SESSION_FILE.parent.mkdir(parents=True, exist_ok=True)
        with open(SESSION_FILE, "w", encoding="utf-8") as f:
            json.dump(self.messages, f, ensure_ascii=False)

    @staticmethod
    def _sanitize_messages(msgs):
        """Clean the history so the API accepts it (400 Bad Request if not):
        1. Assistant with tool_calls MUST be followed by tool messages for each tool_call_id.
           If any are missing, the orphan assistant is removed (wherever it is).
        2. Tool messages without their preceding assistant are removed.
        3. Consecutive user messages are collapsed (last one kept).
        """
        out = []
        pending_ids = set()
        orphan_idx = None  # index in `out` of the last assistant with unresolved tool_calls
        for m in msgs:
            role = m.get("role")
            if role == "assistant" and m.get("tool_calls"):
                pending_ids = {tc.get("id") for tc in m["tool_calls"]}
                orphan_idx = len(out)
                out.append(m)
            elif role == "tool":
                if m.get("tool_call_id") in pending_ids:
                    pending_ids.discard(m["tool_call_id"])
                    if not pending_ids:
                        orphan_idx = None  # resolved
                    out.append(m)
                else:
                    continue  # tool without preceding assistant → discard
            else:
                # A user/normal assistant arrives while tool_calls are unresolved →
                # the orphan assistant is removed
                if pending_ids and orphan_idx is not None:
                    out.pop(orphan_idx)
                    pending_ids = set()
                    orphan_idx = None
                if role == "user" and out and out[-1].get("role") == "user":
                    out[-1] = m  # collapse consecutive users
                else:
                    out.append(m)
        # If tool_calls remain unanswered at the end, remove the orphan assistant
        if pending_ids and orphan_idx is not None:
            out.pop(orphan_idx)
        return out

    def _load_session(self):
        """Load the previous conversation history."""
        if SESSION_FILE.exists():
            try:
                old = json.loads(SESSION_FILE.read_text())
                # Keep original system prompt, concatenate loaded history
                loaded_messages = [m for m in old if m["role"] != "system"]
                loaded_messages = self._sanitize_messages(loaded_messages)
                self.messages.extend(loaded_messages)
                # Compress if loaded history is very long
                texts = [m.get("content", "") for m in self.messages]
                if self._count_tokens(texts) > MAX_HISTORY_TOKENS:
                    self._compress()
            except Exception:
                pass

    def _clean(self, text: str) -> str:
        """Clean think blocks and normalize."""
        text = re.sub(r"<think>.*?</think>\s*", "", text, flags=re.DOTALL).strip()
        return text

    def run(self, query: str) -> str:
        """Wrapper: marks the agent as busy (i3 status bar ⏳) and runs _run."""
        try:
            with open("/tmp/aios-agent.busy", "w") as f:
                f.write("1")
        except Exception:
            pass
        try:
            return self._run(query)
        finally:
            try:
                os.remove("/tmp/aios-agent.busy")
            except Exception:
                pass

    def _run(self, query: str) -> str:
        """Process a query with the function calling loop. First checks procedural memory."""
        if _AUDIO is None:
            _open_audio()
        # Compress history if needed
        self._compress()
        final_response = None

        # 1. Check procedural cache (disabled in pure cloud mode)
        if AIOS_MODE != "cloud":
            cached = self.memory.find(query, self._quick_llm)
            if cached:
                return f"[cache] {cached}"

        self.messages.append({"role": "user", "content": query})

        # Save early so long turns are monitorable/recoverable even if the
        # process dies mid-generation (before final _save_session).
        try:
            self._save_session()
        except Exception:
            pass

        final_response = ""
        empty_retries = 0
        for _ in range(MAX_TURNS):
            # Sanitize before each POST: if a tool call was left orphaned (stream
            # cut or exception mid-way), the API would return 400 Bad Request.
            self.messages = [self.messages[0]] + self._sanitize_messages(self.messages[1:])
            payload = {
                "messages": self.messages,
                "tools": TOOLS,
                "max_tokens": MAX_TOKENS,
                "stream": True,
                **_sampling_params(),
            }
            if AIOS_MODE == "local":
                payload["chat_template_kwargs"] = {"enable_thinking": THINK_LOCAL}
            if AIOS_MODE in ("cloud", "hybrid") and CLOUD_MODEL:
                payload["model"] = CLOUD_MODEL
                payload["chat_template_kwargs"] = {"enable_thinking": THINK_LOCAL}

            try:
                resp = requests.post(LLAMA_SERVER, json=payload, headers=CLOUD_HEADERS, timeout=300, stream=True, verify=VERIFY_TLS)
                resp.raise_for_status()
            except Exception as e:
                return f"LLM connection error: {e}"

            # Total-generation watchdog: even with stream=True the per-read
            # timeout never fires while chunks keep arriving, so a single
            # overzealous reasoning turn can burn 20-40 min. Cap wall time per
            # LLM call at 240s; on expiry, treat it like finish=length.
            _gen_deadline = time.time() + 240

            content_chunks = []
            reasoning_chunks = []
            tool_calls_by_index = {}
            finish_reason = None
            stream_log = None
            fd_cb, old_cb = None, None
            barged = None  # "text" (Tab) or "voice" (Ctrl+R) — user barge-in

            try:
                # Raw stream log (diagnostics for the empty-response bug)
                try:
                    stream_log = open("/tmp/aios-stream.log", "a", encoding="utf-8", errors="replace")
                    stream_log.write(f"\n--- {time.strftime('%H:%M:%S')} mode={AIOS_MODE} ---\n")
                except Exception:
                    stream_log = None

                skip_rest = False  # space during typewriter -> print the rest at once
                fd_cb, old_cb = _cbreak_on()

                for raw_line in resp.iter_lines():
                    # Generation watchdog: kill an overlong single-turn loop.
                    if time.time() > _gen_deadline:
                        if not finish_reason:
                            finish_reason = "length"  # treat as reasoning budget exhausted
                        if stream_log:
                            stream_log.write(f"--- WATCHDOG deadline hit at {time.strftime('%H:%M:%S')} ---\n")
                        break
                    if not raw_line:
                        continue
                    line = raw_line.decode("utf-8")
                    if stream_log:
                        stream_log.write(line + "\n")
                        stream_log.flush()
                    if not line.startswith("data: "):
                        continue
                    data_str = line[6:].strip()
                    if data_str == "[DONE]":
                        break
                    try:
                        data = json.loads(data_str)
                    except json.JSONDecodeError:
                        continue
                    for choice in data.get("choices", []):
                        delta = choice.get("delta", {})
                        if choice.get("finish_reason"):
                            finish_reason = choice["finish_reason"]
                        # Model reasoning (thinking) — stored to return it this turn
                        if "reasoning_content" in delta and delta["reasoning_content"]:
                            reasoning_chunks.append(delta["reasoning_content"])
                        # Live text (typewriter)
                        if "content" in delta and delta["content"]:
                            chunk = delta["content"]
                            content_chunks.append(chunk)
                            if skip_rest:
                                _out(chunk)
                            else:
                                for i, ch in enumerate(chunk):
                                    _out(ch)
                                    _k = _read_key()
                                    if _k == b" ":
                                        _out(chunk[i + 1:])
                                        skip_rest = True
                                        break
                                    if _k in (b"\t", b"\x12"):
                                        barged = "text" if _k == b"\t" else "voice"
                                        skip_rest = True
                                        break
                                    if self.SOUND_ON:
                                        _tic()
                                    time.sleep(0.02)
                                if barged:
                                    break
                        # Tool calls fragmented by index
                        if "tool_calls" in delta:
                            for tc_delta in delta["tool_calls"]:
                                idx = tc_delta.get("index", 0)
                                if idx not in tool_calls_by_index:
                                    tool_calls_by_index[idx] = {
                                        "id": "",
                                        "type": "function",
                                        "function": {"name": "", "arguments": ""},
                                    }
                                if tc_delta.get("id"):
                                    tool_calls_by_index[idx]["id"] = tc_delta["id"]
                                func_delta = tc_delta.get("function", {})
                                if func_delta.get("name"):
                                    tool_calls_by_index[idx]["function"]["name"] += func_delta["name"]
                                if func_delta.get("arguments"):
                                    tool_calls_by_index[idx]["function"]["arguments"] += func_delta["arguments"]
                        if barged:
                            break
                if stream_log:
                    stream_log.write(f"--- END finish={finish_reason} chunks={len(content_chunks)} tools={len(tool_calls_by_index)} barged={barged} ---\n")
            except Exception as e:
                if stream_log:
                    stream_log.write(f"--- EXC {type(e).__name__}: {e} ---\n")
                return f"Error reading LLM stream: {e}"
            finally:
                if stream_log:
                    stream_log.close()
                _cbreak_off(fd_cb, old_cb)

            if barged:
                _out("\n")
                # Barge-in: the user interrupted mid-turn to add info.
                # Preserve what the agent already said, then let chat.py
                # re-enter with the info as a fresh user query.
                if content_chunks:
                    self.messages.append({"role": "assistant", "content": "".join(content_chunks)})
                try:
                    self._save_session()
                except Exception:
                    pass
                if barged == "text":
                    _binfo = _barge_input()
                else:
                    _binfo = ""
                return f"__BARGE__:{barged}:{_binfo}"
            _out("\n")  # newline after the stream (explicit CRLF)
            content = "".join(content_chunks)
            reasoning = "".join(reasoning_chunks)
            msg = {"role": "assistant", "content": content or ""}
            if reasoning:
                msg["reasoning_content"] = reasoning
            if tool_calls_by_index:
                tool_calls = [tool_calls_by_index[i] for i in sorted(tool_calls_by_index)]
                msg["tool_calls"] = tool_calls
            finish = finish_reason or ""

            # Stream ended with no content: retry once if (a) it was cut without
            # finish_reason (connection broke mid-tool-call) or (b) finish=length
            # with empty content (model exhausted max_tokens only reasoning — DeepSeek
            # reasoning_content). With max_tokens already increased this is rare.
            if (not finish or finish == "length") and not content and not msg.get("tool_calls") and empty_retries < 1:
                empty_retries += 1
                print(f"\n  Empty stream ({_empty_reason(finish, reasoning_chunks)}). Retrying...")
                continue

            # Tool call → execute and return result to LLM
            if finish == "tool_calls" or msg.get("tool_calls"):
                assistant_msg = {"role": "assistant", "content": msg.get("content") or ""}
                if msg.get("reasoning_content"):
                    assistant_msg["reasoning_content"] = msg["reasoning_content"]
                if msg.get("tool_calls"):
                    assistant_msg["tool_calls"] = msg["tool_calls"]
                self.messages.append(assistant_msg)

                for tc in msg.get("tool_calls", []):
                    func = tc["function"]
                    name = func["name"]
                    try:
                        args = json.loads(func["arguments"])
                    except json.JSONDecodeError:
                        args = {}


                    # --- Anti-loop FIRST: same tool + same args 3x in a row → stop.
                    # Counts on EVERY call (even ones blocked below), so a model
                    # that insists on the same failing command gets cut at 3
                    # instead of looping forever. Whitespace-stripped args so
                    # minor variations count as the same call. ---
                    _loop_key = (name, func.get('arguments', '').strip())
                    _loop_hist = getattr(self, '_loop_hist', [])
                    _loop_hist.append(_loop_key)
                    if len(_loop_hist) > 9:
                        _loop_hist = _loop_hist[-9:]
                    self._loop_hist = _loop_hist
                    _consec = 0
                    for _k in reversed(_loop_hist):
                        if _k == _loop_key:
                            _consec += 1
                        else:
                            break
                    if _consec >= 3:
                        _out(f"  ⚠ Same tool call repeated {_consec}x — no progress, stopping.\n")
                        # Hard stop: do NOT feed the error back to the LLM as a tool
                        # result. Reasoning models interpret the error as
                        # "command failed, retry" and loop forever. Cut the turn and
                        # return an honest summary to the user instead.
                        final_response = (
                            f"⚠ He repetido la misma llamada a {name} {_consec} veces "
                            f"seguidas sin que el estado cambie, así que corto aquí para "
                            f"no quedarme en bucle. Última llamada: "
                            f"{func.get('arguments', '')[:120]}"
                        )
                        self.messages.append({"role": "assistant", "content": final_response})
                        try:
                            self._save_session()
                        except Exception:
                            pass
                        return final_response

                    # --- Anti-repeat: only guard against blind re-running a command
                    # that ALREADY FAILED with the same command string. Exact-repeat
                    # counting was removed (Sep 2026): it produced false positives on
                    # legitimate retries (e.g. `sven install` after a network timeout)
                    # and crashed with a NameError on `_tool_history`. ---
                    # `continue` (not `break`): skip ONLY this tool call so the
                    # anti-loop above can still count and cut the turn.
                    if name == "run_command":
                        _cmd = args.get('command', '')
                        _last_errors = getattr(self, '_last_run_errors', {})
                        _prev = _last_errors.get(_cmd)
                        if _prev and _prev.get("exit_code") != 0:
                            # Already tried this exact command and it failed; ask model to analyse instead of retrying
                            _out(f"  ⚠ Command already failed before: {_cmd[:60]}...\n")
                            self.messages.append({
                                "role": "tool",
                                "tool_call_id": tc.get("id", "call_0"),
                                "content": json.dumps({
                                    "error": "Command previously failed with the same command string",
                                    "previous_exit_code": _prev.get("exit_code"),
                                    "previous_stderr": _prev.get("stderr", "")[:500],
                                    "instruction": "Do not run the same failing command again. Diagnose the previous error first (e.g. systemctl status, journalctl -u, ls -l)."
                                }, ensure_ascii=False)
                            })
                            continue

                    # Show the tool BEFORE executing (so a long command does not
                    # look like it "does nothing" — the ⚙ is visible immediately).
                    _out(f"  ⚙ {name}({func.get('arguments','')})\n")
                    # Barge-in during tool phase: stop before executing.
                    _bk = _read_key()
                    if _bk in (b"\t", b"\x12"):
                        _bmode = "text" if _bk == b"\t" else "voice"
                        _out("\n")
                        if _bmode == "text":
                            _binfo = _barge_input()
                        else:
                            _binfo = ""
                        return f"__BARGE__:{_bmode}:{_binfo}"
                    result = execute_tool(name, args, context=self.messages)
                    if name == "run_command":
                        r = json.loads(result)
                        out = (r.get('stdout', '') or '').rstrip()[:1000]
                        err = (r.get('stderr', '') or '').rstrip()[:300]
                        if out:
                            _out("     " + out.replace("\n", "\n     ") + "\n")
                        if err:
                            _out("     [stderr] " + err.replace("\n", "\n     ") + "\n")
                        # Store failed command to avoid blind retries
                        if r.get('exit_code') != 0:
                            _last_errors = getattr(self, '_last_run_errors', {})
                            _last_errors[_cmd] = {"exit_code": r.get('exit_code'), "stderr": r.get('stderr', '')}
                            self._last_run_errors = _last_errors

                        # If the command failed due to a systemd dependency, augment the result
                        # with an explicit diagnostic instruction so the model does not loop.
                        _combined = (out + "\n" + err).lower()
                        if "a dependency job for" in _combined and "failed" in _combined:
                            import re as _re
                            _m = _re.search(r"a dependency job for ([^\.]+) failed", _combined)
                            _dep = (_m.group(1).strip() if _m else "the dependency")
                            _extra = (
                                f"\n\n[DIAGNOSTIC HINT] systemd reports that {_dep} failed. "
                                f"Do NOT run the same `systemctl start` command again. "
                                f"First run `sudo systemctl status {_dep}` and `sudo journalctl -u {_dep} --no-pager` to identify the cause. "
                                f"If the failure is because this is a live session (overlay/squashfs), explain that to the user and stop trying to start the service."
                            )
                            r['stdout'] = (r.get('stdout', '') or '') + _extra
                            result = json.dumps(r, ensure_ascii=False)
                            _out("     [systemd dependency detected — stop repeating start]\n")
                    self.messages.append({
                        "role": "tool",
                        "tool_call_id": tc.get("id", "call_0"),
                        "content": result
                    })
                continue  # next iteration: LLM processes the result

            # Final answer (text)
            if msg.get("content"):
                final_response = self._clean(msg["content"])
                assistant_final = {"role": "assistant", "content": final_response}
                if msg.get("reasoning_content"):
                    assistant_final["reasoning_content"] = msg["reasoning_content"]
                self.messages.append(assistant_final)
                # If tools were used, store in procedural memory (only static knowledge)
                had_tools = any(m["role"] == "tool" for m in self.messages[-5:])
                had_dynamic = any("run_command" in m.get("content","") or "read_file" in m.get("content","")
                                  for m in self.messages[-5:])
                if (had_tools and not had_dynamic and final_response
                        and final_response != "I don't know"
                        and not final_response.startswith("(continue)")
                        and len(final_response) >= 80
                        and not _is_trivial_query(query)):
                    self.memory.store(query, final_response, self._quick_llm)
                self._save_session()
                break
            else:
                final_response = f"(empty model response — {_empty_reason(finish, reasoning_chunks)})"
                break

        if not final_response:
            # Turn budget exhausted (no final answer reached): summarize what
            # was done and ask the user whether to continue. Context is kept,
            # so a "yes" continues the work in the next run.
            tools_used = []
            for m in self.messages[1:]:
                for tc in m.get("tool_calls", []) or []:
                    name = tc.get("function", {}).get("name", "")
                    if name and name not in tools_used:
                        tools_used.append(name)
            detail = ", ".join(tools_used) if tools_used else "varias tareas"
            final_response = (
                "(continue) A\u00fan no he terminado tu petici\u00f3n: he estado usando " + detail + ". "
                "\u00bfQuieres que contin\u00fae? (responde 's\u00ed' y seguir\u00e9 donde lo dej\u00e9)"
            )
        return final_response

    def set_think(self, on: bool) -> bool:
        """Enable/disable thinking on the fly (token + max_tokens + system prompt)."""
        global THINK_LOCAL, MAX_TOKENS, SYSTEM_PROMPT
        THINK_LOCAL = on
        self.think = on
        if os.environ.get("AIOS_MODE") in ("cloud", "hybrid"):
            MAX_TOKENS = 4096
        else:
            MAX_TOKENS = max(512, _LOCAL_CONTEXT // 8)
            if THINK_LOCAL:
                MAX_TOKENS = max(2048, _LOCAL_CONTEXT // 8)
        SYSTEM_PROMPT = (_CLOUD_IDENTITY if os.environ.get("AIOS_MODE") in ("cloud", "hybrid") else _LOCAL_IDENTITY) + _AIOS_GROUNDING + _rules_common()
        if self.messages and self.messages[0].get("role") == "system":
            self.messages[0] = {"role": "system", "content": SYSTEM_PROMPT}
        return on

    def reset(self):
        """Reset the conversation."""
        self.messages = [{"role": "system", "content": SYSTEM_PROMPT}]
