"""Software inventory for the AIOS agent.

Tracks installed software per machine in a JSON file (source of truth) plus
per-package markdown fact sheets in ~/.aios/skills/. Auto-updated by a hook
in run_command when install/remove commands succeed — no manual work needed.

- installed_software.json : {pkg: {version, desc, source, installed_at, updated_at}}
- ~/.aios/skills/<pkg>.md  : human-readable fact sheet (commands, notes)

The agent queries it with get_installed_info() — only the relevant fragment
is injected, so it never consumes conversation context.
"""
import json
import os
import re
import subprocess
import time
from pathlib import Path

INVENTORY_FILE = "installed_software.json"
SKILLS_DIR = Path.home() / ".aios" / "skills"

# (regex, source) — order matters: sven first (AIOS), then generic.
_INSTALL_PATTERNS = [
    (re.compile(r"\bsven\s+install\s+([\w.+-]+)"), "sven"),
    (re.compile(r"\bpacman\s+-S(?:y|u|yu|uy)?\s+([\w.+-]+)"), "pacman"),
    (re.compile(r"\bapt(?:-get)?\s+install\s+(?:-y\s+)?([\w.+-]+)"), "apt"),
    (re.compile(r"\bpip(?:3)?\s+install\s+(?:--user\s+)?([\w.+-]+)"), "pip"),
]
_REMOVE_PATTERNS = [
    (re.compile(r"\bsven\s+remove\s+([\w.+-]+)"), "sven"),
    (re.compile(r"\bsven\s+rm\s+([\w.+-]+)"), "sven"),
    (re.compile(r"\bpacman\s+-R(?:n|s|ns)?\s+([\w.+-]+)"), "pacman"),
    (re.compile(r"\bapt(?:-get)?\s+(?:purge|remove)\s+(?:-y\s+)?([\w.+-]+)"), "apt"),
    (re.compile(r"\bpip(?:3)?\s+uninstall\s+(?:-y\s+)?([\w.+-]+)"), "pip"),
]


def _load_inventory() -> dict:
    path = Path(INVENTORY_FILE)
    if path.exists():
        try:
            return json.loads(path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return {}
    return {}


def _save_inventory(data: dict):
    Path(INVENTORY_FILE).write_text(
        json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _pkg_version(pkg: str) -> str:
    """Best-effort version lookup. Returns '' if unknown."""
    for cmd in (
        ["sven", "list", pkg],
        ["pacman", "-Q", pkg],
        ["dpkg", "-s", pkg],
        ["pip3", "show", pkg],
    ):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
            if r.returncode == 0:
                for line in r.stdout.splitlines():
                    if line.lower().startswith(("version", "versión")):
                        return line.split(":", 1)[1].strip()
                return "installed"
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    return ""


def _pkg_desc(pkg: str) -> str:
    """Best-effort description lookup. Returns '' if unknown."""
    for cmd in (
        ["sven", "info", pkg],
        ["pacman", "-Si", pkg],
        ["apt-cache", "show", pkg],
    ):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=10)
            if r.returncode == 0:
                for line in r.stdout.splitlines():
                    if line.lower().startswith(("description", "descripción")):
                        return line.split(":", 1)[1].strip()
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    return ""


def _fact_sheet_path(pkg: str) -> Path:
    return SKILLS_DIR / f"{pkg}.md"


def _write_fact_sheet(pkg: str, version: str, desc: str, source: str):
    """Generate (or refresh) the markdown fact sheet for a package."""
    SKILLS_DIR.mkdir(parents=True, exist_ok=True)
    path = _fact_sheet_path(pkg)
    now = time.strftime("%Y-%m-%d %H:%M")
    lines = [
        f"# {pkg}",
        "",
        f"- **Version**: {version or 'unknown'}",
        f"- **Source**: {source}",
        f"- **Installed/updated**: {now}",
    ]
    if desc:
        lines += ["", f"**Description**: {desc}"]
    lines += [
        "",
        "## Commands",
        "",
        "```bash",
        f"sven info {pkg}   # details",
        f"sven remove {pkg} # uninstall",
        "```",
        "",
        "## Notes",
        "",
        "(auto-generated by aios-agent — edit freely)",
        "",
    ]
    path.write_text("\n".join(lines), encoding="utf-8")


def _remove_fact_sheet(pkg: str):
    path = _fact_sheet_path(pkg)
    if path.exists():
        try:
            path.unlink()
        except OSError:
            pass


def _detect_action(command: str):
    """Return (action, pkg, source) or None."""
    for regex, source in _INSTALL_PATTERNS:
        m = regex.search(command)
        if m:
            return "install", m.group(1), source
    for regex, source in _REMOVE_PATTERNS:
        m = regex.search(command)
        if m:
            return "remove", m.group(1), source
    return None


def update_inventory(command: str, exit_code: int):
    """Hook called by run_command after a command finishes.

    Only acts on successful install/remove commands. Never raises: a failure
    here must not break the agent turn.
    """
    if exit_code != 0:
        return
    try:
        detected = _detect_action(command)
        if not detected:
            return
        action, pkg, source = detected
        data = _load_inventory()
        now = time.time()
        if action == "install":
            version = _pkg_version(pkg)
            desc = _pkg_desc(pkg)
            data[pkg] = {
                "version": version,
                "desc": desc,
                "source": source,
                "installed_at": data.get(pkg, {}).get("installed_at", now),
                "updated_at": now,
            }
            _write_fact_sheet(pkg, version, desc, source)
        else:  # remove
            data.pop(pkg, None)
            _remove_fact_sheet(pkg)
        _save_inventory(data)
    except Exception:
        # Never break the agent turn because of inventory bookkeeping.
        pass


def get_installed_info(pkg: str = "") -> str:
    """Query the software inventory. Returns JSON.

    pkg=''  -> list all installed packages (name + version).
    pkg=X   -> details for one package, including its fact sheet if present.
    """
    data = _load_inventory()
    if not pkg:
        summary = {k: {"version": v.get("version", "")} for k, v in sorted(data.items())}
        return json.dumps({"installed": summary, "total": len(summary)}, ensure_ascii=False)
    if pkg not in data:
        return json.dumps({"error": f"{pkg} not found in inventory"}, ensure_ascii=False)
    entry = dict(data[pkg])
    sheet = _fact_sheet_path(pkg)
    if sheet.exists():
        entry["fact_sheet"] = sheet.read_text(encoding="utf-8", errors="replace")
    return json.dumps({pkg: entry}, ensure_ascii=False)
